language: python
cache:
  directories:
    - $HOME/.cache/pip
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - make setup
  - pip install coveralls

script: make test

after_success:
  coveralls